from __future__ import annotations
from typing import Protocol
from .models import Attachment, Message, ResolvedCourseContext, SessionSummary, Turn
class CourseResolverPort(Protocol):
    def resolve(self, *, turn_id: str, session: SessionSummary, message: str) -> ResolvedCourseContext: ...


class SessionBusyError(RuntimeError):
    """A database-enforced single-active-turn conflict."""
class VisionFeatureDisabledError(RuntimeError):
    """vision 槽位未配置时的附件上传失败。"""
class SessionUseCases(Protocol):
    def list_sessions(self, *, scope_mode: str | None = None, course_id: str | None = None) -> list[SessionSummary]: ...
    def get_session(self, session_id: str) -> SessionSummary | None: ...
    def create_session(self, *, scope_mode: str, course_id: str | None, title: str | None, source: str, owner_id: str = "local-web") -> SessionSummary: ...
    def list_messages(self, session_id: str) -> list[Message]: ...
    def start_turn(self, *, session_id: str, client_request_id: str) -> tuple[Turn, bool]: ...
    def resolve_turn(self, *, turn: Turn, message: str) -> ResolvedCourseContext: ...
    def append_message(self, *, session_id: str, turn_id: str | None, role: str, content: str, citations: list[dict] | None = None, status: str = "complete", activity: list[dict] | None = None) -> Message: ...
    def get_attachments(self, *, session_id: str, attachment_ids: list[str]) -> list[Attachment]: ...
    def complete_turn(self, turn_id: str, *, status: str) -> None: ...
    def touch_turn(self, turn_id: str) -> bool: ...
