from __future__ import annotations
from typing import Protocol
from .artifacts import Artifact, LatestPractice
from .compactions import ConversationSummary
from .models import Attachment, Message, ResolvedCourseContext, SessionSummary, Turn
class CourseResolverPort(Protocol):
    def resolve(self, *, turn_id: str, session: SessionSummary, message: str) -> ResolvedCourseContext: ...


class SessionBusyError(RuntimeError):
    """A database-enforced single-active-turn conflict."""
class VisionFeatureDisabledError(RuntimeError):
    """vision 槽位未配置时的附件上传失败。"""
class SessionUseCases(Protocol):
    def list_sessions(self, *, scope_mode: str | None = None, course_id: str | None = None) -> list[SessionSummary]: ...
    def get_session(self, session_id: str) -> SessionSummary | None: ...
    def create_session(self, *, scope_mode: str, course_id: str | None, title: str | None, source: str) -> SessionSummary: ...
    def delete_session(self, session_id: str) -> None: ...
    def list_messages(self, session_id: str) -> list[Message]: ...
    def start_turn(self, *, session_id: str, client_request_id: str) -> tuple[Turn, bool]: ...
    def resolve_turn(self, *, turn: Turn, message: str) -> ResolvedCourseContext: ...
    def append_message(self, *, session_id: str, turn_id: str | None, role: str, content: str, citations: list[dict] | None = None, status: str = "complete", activity: list[dict] | None = None, choices: list[str] | None = None) -> Message: ...
    def get_attachments(self, *, session_id: str, attachment_ids: list[str]) -> list[Attachment]: ...
    def complete_turn(self, turn_id: str, *, status: str) -> None: ...
    def touch_turn(self, turn_id: str) -> bool: ...


class ArtifactStorePort(Protocol):
    """跨轮产物。agent 只需要这四个动作，不该知道它落在哪张表。"""
    def append(self, *, course_id: str, session_id: str, kind: str, visibility: str, payload: dict) -> Artifact: ...
    def recent(self, *, session_id: str, kind: str | None = None, limit: int = 5) -> list[Artifact]: ...
    def latest_practice(self, *, session_id: str) -> LatestPractice | None: ...
    def practice_digest(self, *, session_id: str) -> str: ...


class CompactionStorePort(Protocol):
    """历史压缩的水位与摘要。"""
    def latest(self, *, session_id: str) -> ConversationSummary | None: ...
    def append(
        self, *, session_id: str, summary_text: str, covers_through_message_id: str,
        covers_through_created_at: str, covers_message_count: int, prompt_version: str, turn_id: str | None,
    ) -> bool: ...
