from __future__ import annotations
from typing import Protocol
from .models import Course
class CourseCatalogPort(Protocol):
    def list_courses(self) -> list[Course]: ...
    def create_course(self, *, name: str, color: str | None = None) -> Course: ...
    def get_course(self, course_id: str) -> Course | None: ...
    def update_course(self, course_id: str, *, wiki_enabled: bool | None = None, name: str | None = None) -> Course | None: ...
